export const getCountryName = (state) => (state.country); 
export const getSearchValue = (state) => (state.search.value);
export const getPlaylistData = (state) => state.playlist;
export const getFavoritePlaylists = (state) => (state.favoritePlaylists);
export const getCurrentFavoritePlaylist = (state) => (state.currentFavoritePlaylist);
export const getFavoriteTracks = (state) => (state.favoriteTracks);
export const getTrack = (state) => (state.track.data);
export const getPlaylistContent = (state) => (state.currentPlaylist.playing.content);
export const getIsPlaying = (state) => (state.track.isPlaying)
export const getBlockedPlaylist = (state) => (state.blockedPlaylists)